[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
ai_registry = "FctTCXPHYieYhvM6Y9mGD61RzHJp3TnppG2wc63avzfp"

[scripts]
test = "npm run test"

[toolchain]
anchor_version = "0.28.0"
